### ISSUE TITLE
install_mistnet_model() downloads corrupted mistnet_nexrad.pt file on Windows

### ISSUE THREAD

**Issue by adokter** [adokter/vol2birdR#12]
On Windows, we have an error thrown at:
https://github.com/adokter/vol2birdR/blob/75d3368ceac67c5b3d1acbd0be46ad7c34a99d1c/mistnet/src/mistnet.cpp#L24

The resultant file size is `539,195,605` while it should be 537,440,829
`download.file()` function to download from s3 uses "wininet" method. Downloading the file with "curl" (not "libcurl") method does work.

From `download.file()` help pages: The "internal" and "wininet" methods do not percent-decode, but the "libcurl" and "curl" methods do

Suggest changing the download method to "curl"

**Comment by adokter** [comment]
@andershenja please verify and confirm fix https://github.com/adokter/vol2birdR/commit/f346510e75c081cfbaddd8990a80c160fb1d144c by closing this issue

**Comment by andershenja** [comment]
Modified to use mode="wb" since the model file is data. Otherwise windows will change binary \r into \r\n

**Comment by andershenja** [comment]
Verified on windows. Closing
