### ISSUE TITLE
update to latest hdf5 version

### ISSUE THREAD

**Issue by adokter** [adokter/vol2birdR#7]
The documentation still lists hdf5@1.10, but I noticed my builds succeed with hdf5@1.12.

**Comment by adokter** [comment]
fixed in https://github.com/adokter/vol2birdR/commit/c0c5c722bfa5e40e923ed0b691e557bc8343ad4d, @andershenja please confirm this fix is ok by closing

**Comment by andershenja** [comment]
OK
